# Generating test data

In [1]:
import os
os.getcwd()
os.chdir("..")
#from survos2.frontend.utils import view_volume
%load_ext autoreload
%autoreload 2

In [2]:
os.getcwd()

'C:\\work\\diam\\SuRVoS2'

In [3]:

import numpy as np
from survos2 import survos
from napari import layers
survos.init_api()
import survos2.frontend.control
from survos2.frontend.control import Launcher
from survos2.model import DataModel
from survos2.improc.utils import DatasetManager


2020-09-08 11:10:33.894 | INFO     | survos2.model.workspace:<module>:25 - CHROOT is c:/work/diam/data/
2020-09-08 11:10:34.820 | DEBUG    | survos2.survos:init_api:50 - API: <hug.api.API object at 0x000001EFBB2DCF78>

2020-09-08 11:10:34.821 | INFO     | survos2.survos:init_api:59 - Config plugins: ['workspace', 'annotations', 'features', 'regions', 'render', 'pipelines']
2020-09-08 11:10:34.822 | INFO     | survos2.survos:init_api:62 - Configuring api plugins
2020-09-08 11:10:34.823 | DEBUG    | survos2.survos:init_api:64 - Loading plugin workspace
2020-09-08 11:10:34.830 | DEBUG    | survos2.survos:init_api:64 - Loading plugin annotations
2020-09-08 11:10:34.832 | DEBUG    | survos2.survos:init_api:64 - Loading plugin features
2020-09-08 11:10:34.835 | DEBUG    | survos2.survos:init_api:64 - Loading plugin regions
2020-09-08 11:10:34.838 | DEBUG    | survos2.survos:init_api:64 - Loading plugin render
2020-09-08 11:10:35.364 | DEBUG    | survos2.survos:init_api:64 - Loading plugin pi

In [4]:
from survos2.server.config import cfg

In [5]:
cfg

{'proj': 'hunt',
 'preprocessing': {},
 'random_seed_main': 32,
 'marker_size': 10,
 'refine_lambda': 1.0,
 'resample_amt': 0.5,
 'save_output_files': False,
 'mscale': 1.0,
 'plot_all': False,
 'roi_crop': [0, 2500, 0, 2500, 0, 2500],
 'torch_models_fullpath': '../experiments',
 'current_annotation': '001_level',
 'filter_cfg': {'superregions1': {'plugin': 'superregions',
   'feature': 'slic',
   'params': {'slic_feat_idx': -1,
    'compactness': 20,
    'postprocess': False,
    'sp_shape': [18, 18, 18]}},
  'filter1': {'plugin': 'features',
   'feature': 'gaussian',
   'params': {'sigma': 2}},
  'filter2': {'plugin': 'features',
   'feature': 'gaussian',
   'params': {'sigma': 2}},
  'filter3': {'plugin': 'features',
   'feature': 'tvdenoising3d',
   'params': {'lamda': 3.7}},
  'filter4': {'plugin': 'features',
   'feature': 'simple_laplacian',
   'params': {'sigma': 2.1}},
  'filter5': {'plugin': 'features',
   'feature': 'gradient',
   'params': {'sigma': 3}}},
 'pipeline': {'cal

In [6]:
test_workspace_name = 'test_s2'

In [7]:
DataModel.g.current_workspace = test_workspace_name

In [8]:
# add data to workspace
survos.run_command('annotations', 'get_labels', uri=None, workspace=test_workspace_name, level='001_level')


2020-09-08 11:02:20.569 | DEBUG    | survos2.survos:run_command:104 - Using client <hug.use.Local object at 0x0000025CBAD7BE08>
2020-09-08 11:02:20.862 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2
2020-09-08 11:02:20.864 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2


c:/work/diam/data/
c:/work/diam/data/


WorkspaceException: Dataset 'default::annotations\001_level' does not exist.

In [16]:
# add data to workspace
survos.run_command('annotations', 'get_levels', uri=None, workspace=test_workspace_name)


2020-09-06 14:00:36.474 | DEBUG    | survos2.survos:run_command:104 - Using client <hug.use.Local object at 0x000001DA0F9624A8>
2020-09-06 14:00:36.928 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2
2020-09-06 14:00:36.928 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2
2020-09-06 14:00:36.969 | INFO     | survos2.survos:run_command:108 - Local client gave response Response(data={'data': [{'kind': 'level', 'labels': {'1': {'color': '#5555ff', 'idx': 1, 'name': 'Label', 'visible': True}, '2': {'color': '#ff007f', 'idx': 2, 'name': 'one', 'visible': True}, '3': {'color': '#12e3cb', 'idx': 3, 'name': 'two', 'visible': True}}, 'modified': [3], 'name': '001 Level', 'id': '001_level'}], 'error': False}, status_code=200, headers={'content-type': 'application/json'})


c:/work/diam/data
c:/work/diam/data


([{'kind': 'level',
   'labels': {'1': {'color': '#5555ff',
     'idx': 1,
     'name': 'Label',
     'visible': True},
    '2': {'color': '#ff007f', 'idx': 2, 'name': 'one', 'visible': True},
    '3': {'color': '#12e3cb', 'idx': 3, 'name': 'two', 'visible': True}},
   'modified': [3],
   'name': '001 Level',
   'id': '001_level'}],
 False)

In [19]:
src = DataModel.g.dataset_uri('001_level', group='annotations')        

In [9]:
dst = DataModel.g.dataset_uri('009_gaussian_blur', group='features')     

In [10]:
src, dst

('survos://default@test_s2:features/006_gaussian',
 'survos://default@test_s2:features/009_gaussian_blur')

In [20]:
with DatasetManager(src, out=src, dtype='uint16', fillvalue=0) as DM:
    src_dataset = DM.sources[0]
    src_arr = src_dataset[:]
    print(src_dataset)
    #DM.out[:] = testvol

2020-09-06 14:04:26.902 | INFO     | survos2.io:survos_from_uri:174 - running survos_from_uri on survos:// uri
2020-09-06 14:04:26.902 | DEBUG    | survos2.io:survos_from_uri:185 - Calling Workspace() Init with workspace name: test_s2
2020-09-06 14:04:26.902 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2
2020-09-06 14:04:26.926 | INFO     | survos2.improc.utils:__init__:495 - DatasetManager setting out to survos://default@test_s2:annotations/001_level
2020-09-06 14:04:26.926 | INFO     | survos2.io:survos_from_uri:174 - running survos_from_uri on survos:// uri
2020-09-06 14:04:26.926 | DEBUG    | survos2.io:survos_from_uri:185 - Calling Workspace() Init with workspace name: test_s2
2020-09-06 14:04:26.926 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2
2020-09-06 14:04:26.991 | INFO     | survos2.improc.utils:__exit__:511 - Closed: <survos2.model.dataset.Dataset object at 0x000001DA1BFD16C8>
2020-09-06 14:04:26.991 | INFO     |

c:/work/diam/data
c:/work/diam/data


In [30]:
src_dataset.metadata()

{'__data__': {'chunk_grid': [1, 1, 1],
  'chunk_size': [99, 256, 256],
  'dtype': 'uint8',
  'fillvalue': 0,
  'shape': [99, 256, 256]},
 'kind': 'level',
 'labels': {1: {'color': '#5555ff',
   'idx': 1,
   'name': 'Label',
   'visible': True},
  2: {'color': '#ff007f', 'idx': 2, 'name': 'one', 'visible': True},
  3: {'color': '#12e3cb', 'idx': 3, 'name': 'two', 'visible': True}},
 'modified': [3],
 'name': '001 Level',
 'somethingelse': [1, 2, 3],
 'geometry': array([1, 2, 3]),
 'geometrydf':    0
 0  1
 1  2
 2  3}

In [24]:
src_dataset.set_attr('somethingelse', [1,2,3])

In [26]:
import pandas as pd

In [ ]:
import numpy as np



In [29]:
src_dataset.set_attr('geometrydf', pd.DataFrame(np.array([1,2,3])))

In [36]:
# add data to workspace
survos.run_command('features', 'existing', uri=None, workspace=test_workspace_name,
                  dtype='float32')


C:/work/diam/data
C:/work/diam/data


({'006_gaussian': {'kind': 'gaussian',
   'name': '006 Gaussian',
   'sigma': [5.0, 6.0, 7.0],
   'source': '__data__',
   'id': '006_gaussian'},
  '007_gaussian_blur': {'kind': 'gaussian_blur',
   'name': '007 Gaussian Blur',
   'sigma': [2.0, 3.0, 4.0],
   'source': '006_gaussian',
   'id': '007_gaussian_blur'},
  '008_laplacian': {'kind': 'laplacian',
   'name': '008 Laplacian',
   'id': '008_laplacian'},
  '009_gaussian_blur': {'kind': 'gaussian_blur',
   'name': '009 Gaussian Blur',
   'id': '009_gaussian_blur'},
  '010_gaussian_blur': {'kind': 'gaussian_blur',
   'name': '010 Gaussian Blur',
   'id': '010_gaussian_blur'}},
 False)

In [33]:
# add data to workspace
survos.run_command('features', 'create', uri=None, workspace=test_workspace_name,
                   
                  feature_type='gaussian_blur')


C:/work/diam/data
C:/work/diam/data
C:/work/diam/data
C:/work/diam/data


({'name': '010 Gaussian Blur',
  'kind': 'gaussian_blur',
  'id': '010_gaussian_blur'},
 False)

In [8]:
src = DataModel.g.dataset_uri('006_gaussian', group='features')        

In [9]:
dst = DataModel.g.dataset_uri('009_gaussian_blur', group='features')     

In [10]:
src, dst

('survos://default@test_s2:features/006_gaussian',
 'survos://default@test_s2:features/009_gaussian_blur')

In [14]:
with DatasetManager(src, out=dst, dtype='float32', fillvalue=0) as DM:
    src_dataset = DM.sources[0]
    src_arr = src_dataset[:]
    print(src_dataset)
    #DM.out[:] = testvol

2020-09-06 13:52:14.721 | INFO     | survos2.io:survos_from_uri:174 - running survos_from_uri on survos:// uri
2020-09-06 13:52:14.721 | DEBUG    | survos2.io:survos_from_uri:185 - Calling Workspace() Init with workspace name: test_s2
2020-09-06 13:52:14.721 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2
2020-09-06 13:52:14.741 | INFO     | survos2.improc.utils:__init__:495 - DatasetManager setting out to survos://default@test_s2:features/009_gaussian_blur
2020-09-06 13:52:14.741 | INFO     | survos2.io:survos_from_uri:174 - running survos_from_uri on survos:// uri
2020-09-06 13:52:14.741 | DEBUG    | survos2.io:survos_from_uri:185 - Calling Workspace() Init with workspace name: test_s2
2020-09-06 13:52:14.741 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_s2
2020-09-06 13:52:14.796 | INFO     | survos2.improc.utils:__exit__:511 - Closed: <survos2.model.dataset.Dataset object at 0x000001DA1BCE7708>
2020-09-06 13:52:14.796 | INFO 

c:/work/diam/data
c:/work/diam/data


In [31]:
src_dataset.get_metadata()

{'__data__': {'chunk_grid': [1, 1, 1],
  'chunk_size': [99, 256, 256],
  'dtype': 'uint8',
  'fillvalue': 0,
  'shape': [99, 256, 256]},
 'kind': 'level',
 'labels': {1: {'color': '#5555ff',
   'idx': 1,
   'name': 'Label',
   'visible': True},
  2: {'color': '#ff007f', 'idx': 2, 'name': 'one', 'visible': True},
  3: {'color': '#12e3cb', 'idx': 3, 'name': 'two', 'visible': True}},
 'modified': [3],
 'name': '001 Level',
 'somethingelse': [1, 2, 3],
 'geometry': array([1, 2, 3]),
 'geometrydf':    0
 0  1
 1  2
 2  3}

In [2]:
import numpy as np
x = np.array([1,2,3])

In [7]:
np.append(x, 4)

array([1, 2, 3, 4])

In [ ]:
with DatasetManager(src, out=dst, dtype='uint32', fillvalue=0) as DM:
    src_dataset = DM.sources[0]
    src_arr = src_dataset[:]
    DM.out[:] = testvol

In [22]:
with DatasetManager(src, out=dst, dtype='uint32', fillvalue=0) as DM:
    out_dataset = DM.out
    out_dataset[:] = test

C:/work/diam/data


WorkspaceException: Dataset 'default::regions\003_supervoxels' does not exist.

In [6]:
import h5py
original_data = h5py.File("D:\\datasets\\mcd_s10_Nuc_Cyt_r1.h5", 'r')
    

In [7]:
original_data['data']

<HDF5 dataset "data": shape (372, 946, 946), type "<f4">

In [13]:
workspace_config = {'dataset_name': "data",
                        'datasets_dir': "D:/datasets/",
                        'vol_fname': 'mcd_s10_Nuc_Cyt_r1.h5',
                        'workspace_name' : 'test_hunt4'}

In [14]:
from survos2.frontend.main import init_ws

In [15]:
init_ws(workspace_config)

2020-09-08 11:12:04.645 | INFO     | survos2.frontend.main:init_ws:66 - Initialising workspace test_hunt4 with image volume D:/datasets/mcd_s10_Nuc_Cyt_r1.h5.
2020-09-08 11:12:04.647 | INFO     | survos2.frontend.main:init_ws:71 - Loaded vol of size (372, 946, 946)
2020-09-08 11:12:11.995 | DEBUG    | survos2.survos:run_command:104 - Using client <hug.use.Local object at 0x000001EF80158458>
2020-09-08 11:12:12.316 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at c:\work\diam\data\test_hunt4
2020-09-08 11:12:12.317 | DEBUG    | survos2.model.workspace:available_sessions:116 - available sessions: no data
2020-09-08 11:12:12.318 | INFO     | survos2.survos:run_command:108 - Local client gave response Response(data={'data': {'path': 'c:\\work\\diam\\data\\test_hunt4', 'data': {}}, 'error': False}, status_code=200, headers={'content-type': 'application/json'})
2020-09-08 11:12:12.319 | INFO     | survos2.frontend.main:init_ws:80 - Created workspace test_hunt4
2020-09-08 

c:/work/diam/data/
c:/work/diam/data/


2020-09-08 11:12:12.615 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_hunt4
2020-09-08 11:12:12.616 | DEBUG    | survos2.model.workspace:__init__:36 - INIT workspace at test_hunt4


c:/work/diam/data/
c:/work/diam/data/


KeyboardInterrupt: 

In [ ]:
with DatasetManager(src, out=dst, dtype='uint32', fillvalue=0) as DM:
    src_dataset = DM.sources[0]
    src_arr = src_dataset[:]
    DM.out[:] = testvol

In [8]:
testvol = np.random.random((99,256,256))# astype(np.uint8)


In [5]:
testvol

array([[[0.16094051, 0.64477902, 0.11246761, 0.52530521],
        [0.41766472, 0.03019242, 0.70697908, 0.9245239 ],
        [0.02184907, 0.26442364, 0.63500628, 0.11733015],
        [0.51228618, 0.75893648, 0.24428915, 0.98520807]],

       [[0.37079193, 0.71295875, 0.69772056, 0.28569361],
        [0.17981007, 0.94798046, 0.37772387, 0.2894099 ],
        [0.95225508, 0.18255298, 0.3561669 , 0.10146895],
        [0.42029368, 0.20069668, 0.36231378, 0.91021364]],

       [[0.43671807, 0.0536361 , 0.34264847, 0.97189999],
        [0.3850615 , 0.96374945, 0.32718722, 0.09799987],
        [0.64538546, 0.08716533, 0.6921055 , 0.79888368],
        [0.99858432, 0.51961402, 0.08161125, 0.38879094]],

       [[0.52336522, 0.68105443, 0.85959642, 0.73278854],
        [0.0261419 , 0.51104359, 0.68292386, 0.91973855],
        [0.8655549 , 0.45079558, 0.18377068, 0.59712437],
        [0.94848778, 0.14270591, 0.84624618, 0.80223913]]])

In [6]:
testvol = np.array([[[0.1761602 , 0.6701295 , 0.13151232, 0.95726678],
        [0.4795476 , 0.48114134, 0.0410548 , 0.29893265],
        [0.49127266, 0.70298447, 0.42751211, 0.08101552],
        [0.73805652, 0.83111601, 0.36852477, 0.38732476]],

       [[0.2847222 , 0.96054574, 0.25430756, 0.35403861],
        [0.54439093, 0.65897414, 0.1959487 , 0.90714872],
        [0.84462152, 0.90754182, 0.02455657, 0.26180662],
        [0.1711208 , 0.40122666, 0.54562598, 0.01419861]],

       [[0.59280376, 0.42706895, 0.86637913, 0.87831645],
        [0.57991401, 0.31989204, 0.85869799, 0.6333411 ],
        [0.21539274, 0.63780214, 0.64204493, 0.74425482],
        [0.1903691 , 0.81962537, 0.31774673, 0.34812628]],

       [[0.40880077, 0.595773  , 0.28856063, 0.19316746],
        [0.03195766, 0.62475541, 0.50762591, 0.34700798],
        [0.98913461, 0.07883111, 0.96534233, 0.57697606],
        [0.71496714, 0.70764578, 0.92294417, 0.91300531]]])

In [7]:
test_datadir = "/dls/science/groups/das/SuRVoS/s2/"

# add dataset to workspace from file, so save array to file
map_fullpath = os.path.join(test_datadir,"testvol_4x4x4c.h5")


with h5py.File(map_fullpath,  'w') as hf:
    hf.create_dataset("data",  data=testvol)


NameError: name 'h5py' is not defined

# Gaussian blur

In [22]:
test_workspace_name = "testing123b"
# create new workspace
survos.run_command("workspace", "create", uri=None, workspace=test_workspace_name)
    
# add data to workspace
survos.run_command('workspace', 'add_data', uri=None, workspace=test_workspace_name,
                 data_fname=map_fullpath,
                  dtype='float32')

# run gaussian_blur    
DataModel.g.current_workspace = test_workspace_name

src = DataModel.g.dataset_uri('__data__', None)
dst = DataModel.g.dataset_uri('001_gaussian_blur', group='features')

survos.run_command('features', 'gaussian_blur', uri=None, 
                  src=src,
                  dst=dst)


/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/


({'done': True}, False)

In [23]:
with DatasetManager(src, out=dst, dtype='float32', fillvalue=0) as DM:
    print(DM.sources[0].shape)
    src_dataset = DM.sources[0]
    dst_dataset = DM.out
    src_arr = src_dataset[:]
    dst_arr = dst_dataset[:]

/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/
(4, 4, 4)


In [24]:
src_arr

array([[[0.16612536, 0.67279379, 0.12032965, 0.9673129 ],
        [0.47731235, 0.47894706, 0.02754662, 0.29205408],
        [0.48933884, 0.70649341, 0.42393911, 0.06853466],
        [0.74246711, 0.837919  , 0.3634353 , 0.38271861]],

       [[0.27747831, 0.97067616, 0.24628176, 0.34857673],
        [0.54382269, 0.66135165, 0.18642259, 0.91590639],
        [0.85177172, 0.91630959, 0.01062425, 0.2539736 ],
        [0.1609564 , 0.3969779 , 0.54508949, 0.        ]],

       [[0.59348014, 0.42348456, 0.87408868, 0.88633289],
        [0.58025901, 0.3135523 , 0.86621007, 0.63505962],
        [0.2063665 , 0.63963535, 0.64398722, 0.74882475],
        [0.18069954, 0.82613296, 0.31135184, 0.3425124 ]],

       [[0.40474673, 0.59652571, 0.28141542, 0.18356984],
        [0.01821561, 0.62625321, 0.5061125 , 0.34136535],
        [1.        , 0.0662941 , 0.97559606, 0.57724553],
        [0.71878414, 0.71127456, 0.93210791, 0.92191354]]])

In [25]:
dst_arr

array([[[0.1334253 , 0.18309763, 0.18128583, 0.13541691],
        [0.19046707, 0.25114629, 0.2388469 , 0.16883893],
        [0.19799377, 0.25374037, 0.23332517, 0.15631635],
        [0.14958453, 0.18756688, 0.16748451, 0.10621871]],

       [[0.18743832, 0.26002762, 0.26079947, 0.1948524 ],
        [0.26292312, 0.35610881, 0.34901825, 0.25268969],
        [0.26981699, 0.3587358 , 0.34435031, 0.24155034],
        [0.20132653, 0.2641314 , 0.24896044, 0.16910219]],

       [[0.1889769 , 0.26528233, 0.26963302, 0.20190974],
        [0.26367947, 0.36606592, 0.36840445, 0.27200189],
        [0.27032515, 0.3715018 , 0.36991027, 0.26886454],
        [0.20220719, 0.27610379, 0.27227667, 0.19469661]],

       [[0.13751902, 0.19435027, 0.19884795, 0.14815024],
        [0.19330847, 0.2737053 , 0.28118965, 0.21023472],
        [0.20052321, 0.28329667, 0.2909368 , 0.21732429],
        [0.15249521, 0.21546596, 0.22105172, 0.16474919]]])

In [ ]:
%%run_pytest[clean] -qq

test_datadir = "D:\\datasets"
test_workspace_name = "testvol_24"
# make test vol
map_fullpath = os.path.join(test_datadir,"testvol_4x4x4b.h5")
#testvol = np.random.random((4,4,4))# astype(np.uint8)
#with h5py.File(map_fullpath,  'w') as hf:
#    hf.create_dataset("data",  data=testvol)

# create new workspace
survos.run_command("workspace", "create", uri=None, workspace=test_workspace_name)
    
# add data to workspace
survos.run_command('workspace', 'add_data', uri=None, workspace=test_workspace_name,
                 data_fname=map_fullpath,
                  dtype='float32')

## add dataset to workspace

# run gaussian_blur    
DataModel.g.current_workspace = test_workspace_name

src = DataModel.g.dataset_uri('__data__', None)
dst = DataModel.g.dataset_uri('001_gaussian_blur', group='features')

survos.run_command('features', 'gaussian_blur', uri=None, 
                  src=src,
                  dst=dst)

with DatasetManager(src, out=dst, dtype='float32', fillvalue=0) as DM:
    print(DM.sources[0].shape)
    src_dataset = DM.sources[0]
    dst_dataset = DM.out
    src_arr = src_dataset[:]
    dst_arr = dst_dataset[:]
    
def test_feature_shape():
    assert dst_arr.shape == (4,4,4)
    
def test_feature_src():    
    assert_allclose(src_arr, np.array([[[0.41955446, 0.65139688, 0.50626089, 0.47356243],
                            [0.5397072 , 0.88715651, 0.57358875, 0.17841908],
                            [0.84062367, 0.42927081, 1.        , 0.601415  ],
                            [0.22624536, 0.61382118, 0.81198787, 0.45563817]],

                           [[0.26604622, 0.98411002, 0.9910637 , 0.04614431],
                            [0.91235452, 0.50873271, 0.9090851 , 0.55183262],
                            [0.69766631, 0.34353716, 0.79863059, 0.81746442],
                            [0.69540008, 0.25363482, 0.        , 0.98832664]],

                           [[0.41824034, 0.2947538 , 0.823542  , 0.02814557],
                            [0.22670235, 0.86729335, 0.28522538, 0.31510756],
                            [0.25549214, 0.1451409 , 0.30383666, 0.74032794],
                            [0.50077333, 0.51566668, 0.30102867, 0.72429019]],

                           [[0.6533611 , 0.66302082, 0.55634748, 0.71185593],
                            [0.94052145, 0.61666328, 0.9143069 , 0.12840489],
                            [0.12144252, 0.84725333, 0.92758133, 0.49322578],
                            [0.54037618, 0.051214  , 0.25104931, 0.87874488]]]))
    
def test_feature_dst():    
    assert_allclose(dst_arr, np.array([[[0.1666268 , 0.2257143 , 0.21892974, 0.14923   ],
                                        [0.22236633, 0.30317545, 0.29989442, 0.21237083],
                                        [0.21442178, 0.29576921, 0.29921022, 0.22003345],
                                        [0.14868982, 0.20833325, 0.21602006, 0.16522714]],

                                       [[0.22320336, 0.30302912, 0.29496408, 0.20176643],
                                        [0.29272896, 0.40102041, 0.39890146, 0.28483036],
                                        [0.27765584, 0.38559583, 0.39318019, 0.2930665 ],
                                        [0.18990593, 0.26771539, 0.2803525 , 0.21866953]],

                                       [[0.21965253, 0.29812005, 0.29064476, 0.19943923],
                                        [0.28396353, 0.39044347, 0.38968769, 0.27962744],
                                        [0.26546711, 0.37147775, 0.38107473, 0.28643546],
                                        [0.17921498, 0.25512561, 0.26955697, 0.21300924]],

                                       [[0.16236468, 0.21962528, 0.21409421, 0.14734329],
                                        [0.20654736, 0.28440154, 0.28422096, 0.20433155],
                                        [0.18955445, 0.26714209, 0.27526605, 0.20778845],
                                        [0.12524115, 0.18044972, 0.19238257, 0.15347627]]]))


In [8]:
import h5py
#from survos2.improc.utils import DatasetManager
from torch.testing import assert_allclose
import numpy as np
testvol = np.random.random((4,4,4))# astype(np.uint8)
testvol

array([[[4.89214115e-01, 4.88751237e-02, 3.94843333e-01, 6.14048171e-01],
        [3.92100031e-01, 6.81171935e-01, 1.81597195e-01, 8.00303290e-01],
        [5.01298600e-01, 5.71608870e-01, 1.22835539e-01, 5.01740551e-01],
        [1.12990600e-01, 7.46636931e-01, 5.20574562e-01, 8.55714714e-01]],

       [[8.12483800e-03, 3.01362385e-03, 4.38506096e-01, 1.93867574e-02],
        [2.56053374e-01, 7.88485971e-01, 3.96912904e-01, 4.79070101e-01],
        [7.29253366e-01, 9.78596473e-01, 4.51489531e-01, 6.20425318e-01],
        [8.67330197e-01, 1.24240882e-01, 7.99268773e-01, 2.08207312e-01]],

       [[9.74542099e-01, 2.74473133e-01, 4.25815244e-01, 1.49041921e-01],
        [1.83750375e-01, 8.15605562e-01, 9.85184681e-01, 2.51071510e-01],
        [8.75301005e-02, 5.27213367e-01, 2.21638196e-01, 6.06119378e-01],
        [5.02913560e-01, 9.94965983e-01, 1.46799760e-01, 3.69431563e-01]],

       [[3.38063000e-01, 2.36308478e-01, 7.47581840e-01, 3.89268267e-02],
        [6.61555719e-01, 9.67296

# Test brain

In [ ]:
#brain
tmpvol_fullpath = "/dls/science/users/xsy37748/data/data.h5"
import h5py
original_data = h5py.File(tmpvol_fullpath, 'r')
    

In [12]:
survos.run_command("workspace", "create", uri=None, workspace='test_s1')

/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/


({'path': '/dls/science/groups/das/SuRVoS/s2/test_s1', 'data': {}}, False)

In [14]:
survos.run_command('workspace', 'add_data', uri=None, workspace='test_s1',
                 data_fname=tmpvol_fullpath, dtype='float32')

/dls/science/groups/das/SuRVoS/s2/
/dls/science/groups/das/SuRVoS/s2/


({'chunk_grid': [1, 1, 1],
  'chunk_size': [99, 256, 256],
  'dtype': 'float32',
  'fillvalue': 0,
  'shape': [99, 256, 256],
  'id': '__data__',
  'path': '/dls/science/groups/das/SuRVoS/s2/test_s1/__data__',
  'name': '__data__'},
 False)